### ISSUE TITLE
Fix TS error in AddModelDialog.tsx 

### ISSUE THREAD

**Issue by mheggelund** [equinor/pepm-ui#117]
Contains a workaround where the file AreaCoordinates.tsx contains a commented out TS error on line 387 +-. The UseEffect complains about how it is set up.

![Image](https://github.com/equinor/pepm-ui/assets/98742460/69767de4-4416-4610-91e3-e94a40728fd4)

**Comment by olavis** [comment]
@mheggelund you can move the function (missing dependency) inside the useEffect to solve the issue, _unless_ the function is used other places as well - then you can wrap the function in a useCallback, add it as a dependency and it should do the same trick. 😇
