### ISSUE TITLE
Add separate page for adding new models

### ISSUE THREAD

**Issue by o-jorgensen** [equinor/pepm-ui#263]
This task includes discarding the dialog for adding new models, and moving the same functionality and more to a separate page.

Derived from https://github.com/equinor/pepm-ui/issues/257.

**Link to Figma design spec:**
https://www.figma.com/file/Ddi81R6qGJINS1M9aPk8dv/PEPM---UI-design?type=design&node-id=3344-78531&mode=design&t=fBIjHky9jaBo93kk-11

**Comment by Sinrefvol** [comment]
@o-jorgensen Missing "Group" after strat.column.

Should be Country -> Field -> Strat.Column -> Group -> Formation -> Zone

**Comment by roar-larsen** [comment]
Closing, duplicate of #265
